gitops-runtime:
  global:
    codefresh:
      accountId: 6838f4cbe8093b51e8117b39
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
