apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codefresh-gitsource
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/Rajesh-git-123/codefresh-node-app.git
      path: k8s-manifests/
      targetRevision: main
      directory:
        include: '**/*.yaml'
        exclude: ''
        recurse: true
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
